env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - "plugin:solid/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'simple-import-sort'
  - 'unused-imports'
  - 'prettier'
  - 'solid'
overrides:
  - files:
      - src/**/*
rules:
  prettier/prettier: warn
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
  no-debugger: warn
  no-console:
    - warn
    - allow: ['warn', 'error']
